name: 'DEV Windows CI'
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - gha/windows
jobs:
  windows:
    name: Windows 10
    runs-on: windows-2019 # Windows Server 2019
    env:
      BOOST_ROOT: ${{github.workspace}}/deps/boost
      BOOST_URL: https://sourceforge.net/projects/boost/files/boost/1.72.0/boost_1_72_0.tar.bz2/download
    steps:
    - name: Restore Boost cache
      uses: actions/cache@v2
      id: cache-boost-win
      with:
          path: ${{env.BOOST_ROOT}}
          key: boost-win
    - name: Install Boost
      if: steps.cache-boost-win.outputs.cache-hit != 'true'
      run: |
          if [ "$OS" == "Windows_NT" ]; then
              # fix up paths to be forward slashes consistently
              BOOST_ROOT=$(echo $BOOST_ROOT | sed 's/\\/\//g')
          fi
          mkdir -p $BOOST_ROOT
          curl --location --output $BOOST_ROOT/download.tar.bz2 $BOOST_URL
          7z -o$BOOST_ROOT x $BOOST_ROOT/download.tar.bz2 -y -bd
          7z -o$BOOST_ROOT x $BOOST_ROOT/download.tar -y -bd
          cd $BOOST_ROOT && cp -r boost_*/* .
          rm -rf boost_*/* download.tar.bz2 download.tar
      shell: bash
    # The next step has a built-in caching mechanism
    - name: Install Vcpkg Dependendencies
      uses: lukka/run-vcpkg@v6
      env:
        vcpkgArgsFile: ${{github.workspace}}/.github/workflows/vcpkg-x86-windows-dependencies
      with:
        vcpkgGitCommitId: 0bf3923f9fab4001c00f0f429682a0853b5749e0
        vcpkgArguments: '@${{env.vcpkgArgsFile}}'
        vcpkgDirectory: '${{github.workspace}}/deps/vcpkg'
        vcpkgTriplet: 'x86-windows'
        appendedCacheKey: ${{hashFiles(env.vcpkgArgsFile)}}-cachekey
    - name: Checkout Project
      uses: actions/checkout@v2
      # FIXME do all the rest
